src/Entity/Produit.php
<?php   
// src/Entity/Produit.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;

    /**
    * @ORM\OneToMany(targetEntity="App\Entity\Contrat", mappedBy="produit")
    */
   private $contrats;

   /**
    */
    public function __construct()
    {
        $this->contrats = new ArrayCollection();
    }

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    // Getters and setters for all properties

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection|Contrat[]
     */
    public function getContrat(): Collection
    {
        return $this->contrats;
    }

    public function addContrat(Contrat $contrat): self
    {
        if (!$this->contrats->contains($contrat)) {
            $this->contrats[] = $contrat;
            $contrat->setProduit($this);
        }

        return $this;
    }

    public function removeContrat(Contrat $contrat): self
    {
        if ($this->contrats->removeElement($contrat)) {
            // set the owning side to null (unless already changed)
            if ($contrat->getProduit() === $this) {
                $contrat->setProduit(null);
            }
        }

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Client;
use App\Entity\Contrat;
use App\Entity\Produit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('nom', TextType::class, [
            'attr' => ['class' => 'form-control'],
            'required' => true, // Adding required attribute
            
        ])
        ->add('date_debut', DateType::class, [
            'widget' => 'single_text',
            'attr' => ['class' => 'form-control'],
            'required' => true, // Adding required attribute
        ])
        ->add('date_fin', DateType::class, [
            'widget' => 'single_text',
            'attr' => ['class' => 'form-control'],
            'required' => true, // Adding required attribute
        ])
        // ->add('contrat', EntityType::class, [
        //     'class' => Contrat::class,
        //     'choice_label' => 'nom',
        //     'multiple' => true,
        //     'expanded' => true,
        //     'attr' => ['class' => 'form-control'],
        // ])
        ->add('client', EntityType::class, [
            'class' => Client::class,
            'choice_label' => 'nom',
            'attr' => ['class' => 'form-control'],
            'required' => true, // Adding required attribute
        ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/produit')]
class ProduitController extends AbstractController
{
    #[Route('/', name: 'app_produit_index', methods: ['GET'])]
    public function index(ProduitRepository $produitRepository): Response
    {
        $produits = $produitRepository->findAll();
        $totalproduits = count($produits);
        // Debugging: Output the fetched products and their clients
        foreach ($produits as $produit) {
            dump($produit->getClient());
        }
        

        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
            'totalproduits' => $totalproduits,
        ]);
    }

    #[Route('/new', name: 'app_produit_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

    $produit = new Produit();
    $form = $this->createForm(ProduitType::class, $produit);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {

        $entityManager->persist($produit);
        $entityManager->flush();
        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }

    return $this->renderForm('produit/new.html.twig', [
        'produit' => $produit,
        'form' => $form,
    ]);
    }

    #[Route('/{id}', name: 'app_produit_show', methods: ['GET'])]
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produit_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
            $this->addFlash('success', 'Modifié avec succès');

            return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produit_delete', methods: ['POST'])]
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->request->get('_token'))) {
            $this->addFlash('success', 'Supprimer avec succès');

            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_produit_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('app_produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-outline-danger btn-back">Supprimer</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
<div class="form-group">
    {{ form_label(form.nom) }}<span style="color: red;"> *</span>
    {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
    {{ form_errors(form.nom) }}
</div>
<div class="form-group">
    {{ form_label(form.date_debut) }}<span style="color: red;"> *</span>
    {{ form_widget(form.date_debut, {'attr': {'class': 'form-control'}}) }}
    {{ form_errors(form.date_debut) }}
</div>
<div class="form-group">
    {{ form_label(form.date_fin) }}<span style="color: red;"> *</span>
    {{ form_widget(form.date_fin, {'attr': {'class': 'form-control'}}) }}
    {{ form_errors(form.date_fin) }}
</div>
<div class="form-group">
    {{ form_label(form.client) }}<span style="color: red;"> *</span>
    {{ form_widget(form.client, {'attr': {'class': 'form-control'}}) }}
    {{ form_errors(form.client) }}
</div>
<button type="submit" class="btn btn-outline-success btn-back">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ produit.nom }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ produit.dateDebut ? produit.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ produit.dateFin ? produit.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Contrats</th>
                <td>{% for contrat in produit.contrat %} {{ contrat.nom }}{% endfor %}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_produit_index') }}">back to list</a>

    <a href="{{ path('app_produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}